#!/usr/bin/env python3
"""
state_codec.py — .dev-kit/state.json ↔ hand-off markdown conversion.

Single source of truth for global state. Per MUST-22 dual-source SSOT:
- CLAUDE.md §2 active stage (auto-loaded into context)
- .dev-kit/state.json (machine-readable, atomic write)

Atomic write: write to .tmp then rename (POSIX atomic).
"""
from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Dict, List, Optional

KST = timezone(timedelta(hours=9))
SCHEMA_VERSION = "1.0.0"


def now_iso() -> str:
    return datetime.now(KST).strftime("%Y-%m-%dT%H:%M:%S%z")


def read_state(project_root: Path) -> Dict:
    """Read .dev-kit/state.json. Returns default if missing."""
    state_path = project_root / ".dev-kit" / "state.json"
    if not state_path.exists():
        return {
            "schema_version": SCHEMA_VERSION,
            "project": project_root.name,
            "current_stage": "bootstrap",
            "current_step": 1,
            "last_transition_at": now_iso(),
            "hand_off_chain": [],
            "loop_log_path": str(project_root / ".dev-kit" / "loop-log.json"),
            "shortcut_used": None,
            "claude_md_sha": None,
        }
    return json.loads(state_path.read_text(encoding="utf-8"))


def write_state(project_root: Path, state: Dict) -> None:
    """Atomic write to .dev-kit/state.json. POSIX atomic via rename."""
    state_path = project_root / ".dev-kit" / "state.json"
    state_path.parent.mkdir(parents=True, exist_ok=True)
    state["last_transition_at"] = now_iso()
    state["schema_version"] = SCHEMA_VERSION
    fd, tmp_path = tempfile.mkstemp(
        dir=state_path.parent,
        prefix=".state.",
        suffix=".json.tmp",
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(state, f, indent=2, ensure_ascii=False, sort_keys=True)
        os.replace(tmp_path, state_path)
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise


def transition_stage(
    project_root: Path,
    new_stage: str,
    step: int = 1,
    shortcut: Optional[str] = None,
) -> Dict:
    """Mark stage transition. Updates state + records into hand-off chain."""
    state = read_state(project_root)
    old_stage = state["current_stage"]
    state["current_stage"] = new_stage
    state["current_step"] = step
    state["shortcut_used"] = shortcut
    state["hand_off_chain"].append({
        "from": old_stage,
        "to": new_stage,
        "at": now_iso(),
        "step": step,
    })
    write_state(project_root, state)
    return state


def append_hand_off(project_root: Path, from_stage: str, to_stage: str, goal: str) -> Path:
    """Append hand-off markdown file. Idempotent (no overwrite)."""
    hand_off_dir = project_root / ".dev-kit" / "hand-off"
    hand_off_dir.mkdir(parents=True, exist_ok=True)
    fname = f"{from_stage}→{to_stage}.md"
    path = hand_off_dir / fname
    if path.exists():
        return path  # idempotent
    content = f"""# Hand-off: {from_stage} → {to_stage}

> Auto-generated by `state_codec.transition_stage()` at {now_iso()}.

## §1 Goal
{goal}

## §2 1-line Summary
(전 단계 완료 요약 — AI가 다음 단계 진입 시 자동 작성)

## §3 Open Issues
(none — 모든 gate 통과한 경우)

## §4 Next Stage Trigger
`/dev-kit:{to_stage}` (0-arg). Preamble 자동 주입: CLAUDE.md §2 + 이 hand-off.
"""
    fd, tmp_path = tempfile.mkstemp(dir=hand_off_dir, prefix=".hand-off.", suffix=".md.tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp_path, path)
    except Exception:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)
        raise
    return path


if __name__ == "__main__":
    import sys
    root = Path(os.environ.get("PROJECT_ROOT", "."))
    if len(sys.argv) < 2:
        print("usage: state_codec.py {read|transition|hand-off} ...", file=sys.stderr)
        sys.exit(1)
    cmd = sys.argv[1]
    if cmd == "read":
        print(json.dumps(read_state(root), indent=2, ensure_ascii=False))
    elif cmd == "transition" and len(sys.argv) >= 3:
        new_state = transition_stage(root, sys.argv[2])
        print(json.dumps(new_state, indent=2, ensure_ascii=False))
    elif cmd == "hand-off" and len(sys.argv) >= 5:
        path = append_hand_off(root, sys.argv[2], sys.argv[3], sys.argv[4])
        print(f"wrote {path}")
    else:
        print(f"unknown command: {cmd}", file=sys.stderr)
        sys.exit(1)
